version: '2.0' 

services: # Anfang der Services
  mysql:  # Erster Service
    image: mysql:5.7  # Docker Image und Version
    container_name: mysql # Name des Containers
    volumes:
      - db_data:/var/lib/mysql  # Verwendetes Volume wird angegeben
    networks:
      - dockernetwork # Verwendetes Netzwerk wird angegeben
    restart: always # Der Container wird nach der Erstellung neu gestartet
    environment:
      MYSQL_ROOT_PASSWORD: 'test1234' # mysql-Rootpassword ändern
      MYSQL_DATABASE: testdatabase # Test-DB erstellen
      MYSQL_USER: testuser  # Test-SQL-User erstellen
      MYSQL_PASSWORD: testpw  # User ein Passwort geben

  phpmyadmin:
    depends_on:
      - mysql # Dieser Container ist abhängig vom Container mysql
    image: phpmyadmin/phpmyadmin # Docker Image, Version ist latest
    container_name: phpmyadmin  # Name des Containers
    networks:
      - dockernetwork # Verwendetes Netzwerk wird angegeben
    ports:
      - "80:80" #Port forward auf Port 80 der VM
    restart: always # Der Container wird nach der Erstellung neu gestartet
    environment:
      PMA_HOST: mysql # verlinkung zu Db-Container angeben

volumes:
  db_data: {} # Neues Volume erstellen

networks:
  dockernetwork:  # Neues Netzwerk erstellen
